### ISSUE TITLE
Při přiřazování bloků si pamatovat poslední zvolenou oblast řízení

### ISSUE THREAD

**Issue by petrilakm** [kmzbrnoI/hJOPeditor#19]
Při přiřazování bloků (režim = bloky) si pamatovat poslední zvolenou oblast řízení.
Při otevření okýnka s výběrem bloků je v roletce "oblast řízení" vždy vybrána první volba.
Editaci by hodně zpřijemnilo, kdyby se sama vybrala volba od předešlého bloku.

**Comment by malinajan** [comment]
Mně se moc nelíbí vlastnost, že pouhé otevření okna přiřazení bloku + oblasti řízení by změnilo oblast řízení bloku. To je podle mě neintuitivní chování - když se okno otevře, čekám, že jen uvidím aktuální stav.

Souhlasím, že přiřazování oblastí řízení je otravná činnost. Navrhuji implementovat nový subrežim řežimu "bloky", ve kterém se bude dát hromadně přiřadit oblast řízení. Vybereš kurzorem libovolný obdélník na reliéfu a všem blokům v tomto obdélníku budeš moct hromadně přiřadit tebou vybranou oblast řízení. Navíc bych implementoval, že v tomto režimu budou mít bloky každé oblasti řízení různou barvu, takže si může uživatel hezky vizuálně zkontrolovat, že má přiřazené oblasti řízení správně.

**Comment by malinajan** [comment]
Implementováno.
